"""empty message

Revision ID: 4c6f3a1626b2
Revises: ac43122a27da
Create Date: 2018-07-12 18:31:12.978595

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4c6f3a1626b2'
down_revision = 'ac43122a27da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('emails', postgresql.ARRAY(sa.String(length=120)), nullable=True))
    op.add_column('contact', sa.Column('phone_numbers', postgresql.ARRAY(sa.String(length=30)), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'phone_numbers')
    op.drop_column('contact', 'emails')
    # ### end Alembic commands ###
