"""empty message

Revision ID: ac43122a27da
Revises: 
Create Date: 2018-07-12 02:09:40.684414

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ac43122a27da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('addresses', postgresql.ARRAY(sa.String(length=200)), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'addresses')
    # ### end Alembic commands ###
